### ISSUE TITLE
Missing srcipts from pacakge.json

### ISSUE THREAD

**Issue by tiborsaas** [CookieCollective/4k-Demo-Oven#1]
Hello,

I wanted to check out this nifty framework, but `package.json` misses the scripts section required to do anything so I have little clue how to move forward.

Any help would be appreciated.

**Comment by KoltesDigital** [comment]
Hey!

You're right, I forgot to update the doc. I changed the build system and switched to Gulp. I've updated the Readme, please have a look.

Also, this project is working, but is deprecated and won't receive any new feature. I'm working on [https://github.com/KoltesDigital/shiba](Shiba), which will have the same features and much more! It's almost ready.

**Comment by tiborsaas** [comment]
Thank you very much :)
